name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Sutil/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: github-contribution-grid-snake.svg
          snake_color: 'orange'

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: svgs
          build_dir: Â©svgs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
